first crack at the sample data
deephaven/examples pull request #1
Opened 2021-05-04 22:12 UTC by mikeblas

might end up compressing these -- for now, it doesn't quite seem worth it

2021-05-06 15:31 UTC, chipkent requested changes

2021-05-06 20:23 UTC, mikeblas commented on iris/iris.csv
> +SepalLengthCM,SepalWidthCM,PetalLengthCM,PetalWidthCM,Class
No need to just yet; all files are under 10 megs -- GitHub starts to warn at 50 megs, and I read that it will start to fail at 100 megs.

2021-05-06 20:27 UTC, mikeblas commented on iris/README.md
> +This sample contains the observations about iris sepal and petal length from R A Fisher's classic 1950 paper, "The use of multiple measurements in taxonomic problems". The paper describes the use of
fixed!

2021-05-06 20:28 UTC, mikeblas commented on gsod/README.md
> +The `station_data.csv` file describes each observation station; there are data files name after each city where the observations were made. Because stations began recording data at different times, t
fixed!

2021-05-06 20:30 UTC, mikeblas commented on README.md
> +
With the docker sample script written, we've changed a bit -- I don't have uncompressed data in this repository and instead it contains `README.md` files and `*.tar.gz` files.  Should it contain both uncompressed data *and* the compressed data, both?

2021-05-06 20:30 UTC, mikeblas commented on metriccentury/README.md
> +The set has 16987 observations that span five hours, 36 minutes of elapsed time.
I used "five hours and 36 minutes" for now, pending input from Margaret.

2021-05-07 15:30 UTC, margaretkennedy commented on metriccentury/README.md
> +The set has 16987 observations that span five hours, 36 minutes of elapsed time.
That is what I suggested above; sounds good to me

2021-05-10 20:04 UTC, mikeblas commented on iris/README.md
> +# Iris Data
I believe so -- I went through and compared what I saw in the previous instance/version of this PR.

2021-05-11 16:54 UTC, chipkent commented on README.md
> +
I need to look at the other repo -- possibly first.  My inclination is that we should not have tgz files in the repo.  The repo should just check out and be human usable.

2021-05-11 16:59 UTC, devinrsmith commented on README.md
> +
We could consider uploading the data to a google or aws bucket and make it public.

2021-05-18 21:15 UTC, mikeblas commented on README.md
> +
I went ahead and made the directories.

2021-05-18 21:58 UTC, chipkent requested changes

2021-05-18 21:58 UTC, chipkent commented on metriccentury/README.md
> +- Sensors may occasional report unlikely or impossible values.
```suggestion
- Sensors may occasionally report unlikely or impossible values.
```

2021-05-19 14:05 UTC, mikeblas commented on README.md
> +
header was fixed

2021-05-19 15:46 UTC, merged