more details for examples script container
deephaven/examples pull request #20
Opened 2021-07-20 18:46 UTC by mikeblas

2021-07-20 18:54 UTC, dsmmcken approved these changes
That helped, thanks.

2021-07-20 20:41 UTC, chipkent requested changes

2021-07-20 20:41 UTC, chipkent commented on README.md
> +The `docker build` command builds a Docker container which hosts a script that helps manage the examples. That script will automate the management of the example files, allowing you to download and u
```suggestion
The `docker build` command builds a Docker container containing a script that helps manage the examples. 
 That script will automate the management of the example files.  It allows you to download and update the example files without directly working with the git project hosting the examples.  This `docker build` command is only needed once; after it runs, the container is available to use on your host.
```

2021-07-20 20:41 UTC, chipkent commented on README.md
> +The `docker run` command runs that new container, letting it know that the examples will end up in your `deephaven-core/docker/core/data` path. When Deephaven runs in its containers, this directory f
```suggestion
The `docker run` command downloads the example data by running the new examples management container.  The `-v "$(pwd)/docker/core/data:/data"` argument mounts your local `deephaven-core/docker/core/data` path as `/data` in the container.  The example data is stored to `/data/examples` inside the container, which is `deephaven-core/docker/core/data/examples` on the local filesystem.
```

2021-07-20 20:41 UTC, chipkent commented on README.md
> +will run the contained script and show usage for the different commands it offers.
```suggestion
You can run `docker run` again to manage the example data -- for example, to download a new version. To see what options are available, run:

	`docker run --rm -v "$(pwd)/docker/core/data:/data" deephaven/examples`
```

2021-07-22 15:49 UTC, chipkent approved these changes

2021-08-06 15:05 UTC, chipkent approved these changes

2021-08-06 20:33 UTC, merged