Credit card fraud dataset
deephaven/examples pull request #60
Opened 2021-10-08 20:52 UTC by jjbrosnan

Contains all necessary information and citations.

2021-10-08 20:53 UTC, jjbrosnan commented
I have read the CLA Document and I hereby sign the CLA

2021-10-08 21:15 UTC, jakemulf submitted a review, later dismissed

2021-10-09 10:56 UTC, margaretkennedy requested changes

2021-10-09 10:56 UTC, margaretkennedy commented on CreditCardFraud/README.md
> +This directory contains a [credit card purchase dataset](https://www.kaggle.com/mlg-ulb/creditcardfraud).  The data set contains anonymized parameters for 48 hours worth of purchases by European card
```suggestion
This directory contains a [credit card purchase dataset](https://www.kaggle.com/mlg-ulb/creditcardfraud) with anonymized parameters for 48 hours worth of purchases by European cardholders.  There are 284,807 purchases in total, and 492 of them are fraudulent.
```

2021-10-09 10:56 UTC, margaretkennedy commented on CreditCardFraud/README.md
> +# Credit Card Fraud Data
```suggestion
# Credit card fraud data
```

2021-10-09 10:56 UTC, margaretkennedy commented on CreditCardFraud/README.md
> +- **Class** - A flag indicating a valid (0) or fraudulent (1) purchase
```suggestion
- **Class** - A flag indicating a valid (0) or fraudulent (1) purchase.
```

2021-10-09 10:56 UTC, margaretkennedy commented on CreditCardFraud/README.md
> +This data is taken directly from [Kaggle](https://kaggle.com).  It is provided here for demonstrative use without any warranty as to the accuracy, reliability, or completeness of the data.  Credit fo
```suggestion
This data is taken directly from [Kaggle](https://kaggle.com).  It is provided here for demonstrative use without any warranty as to the accuracy, reliability, or completeness of the data.  

Credit for the dataset goes to:
```

2021-10-09 10:56 UTC, margaretkennedy commented on CreditCardFraud/README.md
> +This data is taken directly from [Kaggle](https://kaggle.com).  It is provided here for demonstrative use without any warranty as to the accuracy, reliability, or completeness of the data.  Credit fo
This looks more like a Works Cited List. How about, "The following sources contributed to this dataset:"

2021-10-09 10:56 UTC, margaretkennedy commented on CreditCardFraud/README.md
> +Andrea Dal Pozzolo, Olivier Caelen, Reid A. Johnson and Gianluca Bontempi. [Calibrating Probability with Undersampling for Unbalanced Classification](https://www.researchgate.net/publication/28334913
```suggestion
Dal Pozzolo, Andrea,  Olivier Caelen, Reid A. Johnson and Gianluca Bontempi. [Calibrating Probability with Undersampling for Unbalanced Classification](https://www.researchgate.net/publication/283349138_Calibrating_Probability_with_Undersampling_for_Unbalanced_Classification). In Symposium on Computational Intelligence and Data Mining (CIDM), IEEE, 2015
```

2021-10-09 10:56 UTC, margaretkennedy commented on CreditCardFraud/README.md
> +Carcillo, Fabrizio; Dal Pozzolo, Andrea; Le Borgne, Yann-Aël; Caelen, Olivier; Mazzer, Yannis; Bontempi, Gianluca. [Scarff: a scalable framework for streaming credit card fraud detection with Spark](
can we alphabetize this? Bertrand first

2021-10-12 15:47 UTC, chipkent requested changes

2021-10-12 15:47 UTC, chipkent commented on CreditCardFraud/README.md
> +This directory contains a [credit card purchase dataset](https://www.kaggle.com/mlg-ulb/creditcardfraud) with anonymized parameters for 48 hours worth of purchases by European cardholders.  There are
```suggestion
This directory contains a [credit card purchase dataset](https://www.kaggle.com/mlg-ulb/creditcardfraud) with anonymized parameters.  48 hours of purchases by European cardholders are recorded.  There are 284,807 purchases in total, and 492 of them are fraudulent.
```

2021-10-12 15:47 UTC, chipkent commented on CreditCardFraud/README.md
> +This data is taken directly from [Kaggle](https://kaggle.com).  It is provided here for demonstrative use without any warranty as to the accuracy, reliability, or completeness of the data.
```suggestion
This data was obtained from [Kaggle](https://kaggle.com).  It is provided here for demonstrative use without any warranty as to the accuracy, reliability, or completeness of the data.  
```

2021-10-12 15:47 UTC, chipkent commented on README.md
> +- **[`CreditCardFraud`](./CreditCardFraud)** - Anonymized credit card purchase data including fraudulent purchases.
```suggestion
- **[`CreditCardFraud`](./CreditCardFraud)** - Anonymized credit card purchase data, including fraudulent purchases.
```

2021-10-12 20:52 UTC, chipkent approved these changes

2021-10-13 17:29 UTC, merged