Insurance data set
deephaven/examples pull request #62
Opened 2021-10-11 14:49 UTC by jjbrosnan

Contains readme and updates to base readme

2021-10-11 14:53 UTC, margaretkennedy requested changes

2021-10-11 14:53 UTC, margaretkennedy commented on Insurance/README.md
> +`Expenses` - The patient's insurance expenses# Insurance dataset
```suggestion
`Expenses` - The patient's insurance expenses
```

2021-10-11 14:53 UTC, margaretkennedy commented on Insurance/README.md
> +This folder contains one sub-folder, `csv`, which contains the `insurance.csv` file.  This file contains health indicators of patients and their insurance charges.  These can be used to predict insur
accidentally duplicated?

2021-10-12 15:39 UTC, chipkent requested changes

2021-10-12 15:39 UTC, chipkent commented on Insurance/README.md
> +This folder contains one sub-folder, `csv`, which contains the `insurance.csv` file.  This file contains health indicators of patients and their insurance charges.  These can be used to predict insur
```suggestion
This folder contains one sub-folder, `csv`, which contains the `insurance.csv` file.  This file contains health indicators of patients and their insurance charges.  These can be used to predict insurance charges based upon health indicators.
```

2021-10-12 15:39 UTC, chipkent commented on Insurance/README.md
> +This data was built from [Kaggle](https://kaggle.com).  The original link, authored by Brandon Yong, can be found [here](https://www.kaggle.com/brandonyongys/insurance-charges/notebook#Basic-data-inf
```suggestion
This data was obtained from [Kaggle](https://kaggle.com).  The original analysis and data, authored by Brandon Yong, can be found [here](https://www.kaggle.com/brandonyongys/insurance-charges/notebook#Basic-data-information).  This data is provided here for demonstrative use without any warranty as to the accuracy, reliability, or completeness of the data.
```

2021-10-13 17:30 UTC, merged